---
AWSTemplateFormatVersion: "2010-09-09"

Description: 
 "Amazon Web Services S3 Bucket with encryption built on CloudFormation"

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256


      BucketName: !Sub "cloudformationbucket-${AWS::AccountId}-${AWS::Region}"


